var e;
if(!window.__idm_init__&&navigator.platform.startsWith("Win")&&"html"==document.documentElement.localName){window.__idm_init__=!0;Array.prototype.includes||(Array.prototype.includes=function(a,b){return 0<=this.indexOf(a,b)});Array.prototype.H||(Array.prototype.H=function(a){0>a&&(a+=this.length);return this[a]});NodeList.prototype[Symbol.iterator]||(NodeList.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);HTMLCollection.prototype[Symbol.iterator]||(HTMLCollection.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);
"undefined"==typeof browser&&(browser=chrome);navigator.userAgent.includes("Edge/");navigator.userAgent.includes("Firefox/");navigator.userAgent.includes("OPR/");var w=Object.values,D=RegExp.prototype.test,E=Array.from,F=Array.prototype.includes,H=Function.call.bind(Array.prototype.slice),I=Function.apply.bind(Array.prototype.push),J=Function.call.bind(Array.prototype.forEach),K={16:!0,17:!0,18:!0,45:!0,46:!0},L=F.bind(["video","audio","object","embed"]),M=/(?!)/,R=/ *[$~]([<>{}&*+=@!#%:?^~-])(\d*) */,
S=D.bind(/^rgba?\(\d+,\s*\d+,\s*\d+,\s*0\)/),T=window.self===window.top,U=window.origin||document.origin||location.origin,V=location.hostname.toLowerCase().split(".").H(-2),W="idmrs://"+V+"/",X=V?RegExp("^(?:\\(\\d+\\)\\s+)?(.+?)\\s+[-|@]+\\s*"+V+"$","i"):M;function N(){browser.runtime.Ta?this.ca=browser.runtime.Ta(window):T&&(this.ca=0);this.ha=[];this.da=[];this.N=new Map;this.m={};this.Qa();window.__idm_connect__=this.Qa.bind(this,!0);this.b(1,window,"resize",this.Vb);this.b(1,window,"scroll",
this.Wb);this.b(1,window,"blur",this.Nb);this.b(1,window,"keydown",this.$a,!0);this.b(1,window,"keyup",this.$a,!0);this.b(1,window,"mousedown",this.Pb,!0);this.b(1,window,"mouseup",this.Rb,!0);this.b(1,window,"mousemove",this.Qb,!0);this.b(1,window,"click",this.Ob,!0);this.b(1,document,"beforeload",this.Lb,!0);this.b(1,document,"DOMContentLoaded",this.Za);"interactive"!=document.readyState&&"complete"!=document.readyState||this.Za()}e=N.prototype;e.g=0;e.l=0;e.ka=-1;e.la=-1;e.gb=1;e.S=0;e.f="";e.Ga=
"";e.G="";e.Ia=M;e.Ma=M;e.U=M;e.Oa=/^\/(?:watch\?(?:.*?&)?v=|shorts\/|embed\/)([\w-]{10,12})(?:[/?&#]|$)/;e.A={};e.Ja=M;e.Ka=M;e.La=M;e.Na='$> *[role="main"]:not(hidden) video';e.V="$< div#inline-preview-player $< a#media-container-link";e.ua=M;e.pa=":root:empty";e.sa='div[id^="mount_0_"] >div:is([class=""],:not([class])) >div[class=""] >div:first-child';e.i=":root:empty";e.ta=":root:empty";e.u=":root:empty";e.j="$< div >:not(:only-child):not(video:first-child,img:first-child:nth-last-child(2)) <";
e.va="$> div[data-video-id] $= data-video-id";e.oa="a:not([target])";e.v=":root:empty";e.ra=4;e.qa=M;e.xa=M;e.Ea=":root:empty";e.ya='$& div.xxzkxad $& section main[role="main"] $& div.xw7yly9 >div >div[style]:only-child $& div >article <';e.Ba='$& div.xxzkxad $& section main[role="main"] $& div:first-child >div[role="button"][aria-hidden], article[role="presentation"] $& div:first-child >div[style]:first-child:empty < $& div[role="presentation"] >div >ul';e.Fa="$& div.xxzkxad $& section.x5qyhuo $& :scope >div >div:only-child $& section >div";
e.wa='$+ article:scope $* main[role="main"] article';e.Aa='$& div[role="dialog"] div[role="dialog"] >div $& div:first-child >div[style]:first-child:empty < $& div[role="presentation"] >div >ul';e.T="$* video";e.Ca='$= poster ${ div[role="presentation"] >div >ul $<< $>:scope >div[data-instancekey] img $= src';e.Da="*.return.return.memoizedProps.videoFBID";e.za=/\/(?:p|reel)\/([\w-]{11})(?:[/?#]|$)/;e.Ha=M;e.Qa=function(a){this.bb(-1);this.a=a=browser.runtime.connect({name:(T?"top":"sub")+(a?":retry":
"")+("file:"==location.protocol?":file":"")});this.b(-1,a,"onMessage",this.Tb);this.b(-1,a,"onDisconnect",this.Sb)};e.Sb=function(){browser.runtime.lastError;this.bb();this.a=this.ea=null;window.__idm_init__=!1;window.__idm_connect__=null};e.Tb=function(a){switch(a.shift()){case 11:this.ub.apply(this,a);break;case 17:this.vb.apply(this,a);break;case 12:this.wb.apply(this,a);break;case 13:this.mb=a.shift();break;case 14:this.zb.apply(this,a);break;case 15:this.Ab.apply(this,a);break;case 16:this.Bb.apply(this,
a);break;case 18:this.yb.apply(this,a)}};e.Yb=function(a,b){var c=94<=this.kb;switch(this.o=a){case 1:this.B=this.nb=!0;if(a=b.shift())this.f=a;if(a=b.shift())this.Ia=RegExp(a,"s");if(a=b.shift())this.U=RegExp(a);if(a=b.shift())this.Oa=RegExp(a);if(a=b.shift())this.A=a.split(/[|:]/).reduce(Z,{});if(a=b.shift())this.Ja=RegExp(a);if(a=b.shift())this.Ka=RegExp(a);if(a=b.shift())this.La=RegExp(a);if(a=b.shift())this.Ma=RegExp(a,"s");if(a=b.shift())this.Na=a;if(a=b.shift())this.V=a;break;case 2:this.B=
!0;if(a=b.shift())this.f=a;if(a=b.shift())this.G=a;if(a=b.shift())this.ua=RegExp(a);if(a=b.shift())this.pa=a;(a=b.shift())&&c&&(this.sa=a);b.shift();if(a=b.shift())this.i=a;if(a=b.shift())this.ta=a;if(a=b.shift())this.u=a;if(a=b.shift())this.j=a;if(a=b.shift())this.va=a;if(a=b.shift())this.oa=a;if(a=b.shift())this.v=a;(a=b.shift())&&c&&(this.ra=a);if(a=b.shift())this.ib=a;if(a=b.shift())this.qa=RegExp(a);break;case 4:this.B=!0;if(a=b.shift())this.f=a;if(a=b.shift())this.Ga=a;if(a=b.shift())this.G=
a;if(a=b.shift())this.xa=RegExp(a);if(a=b.shift())this.Ea=a;if(!c)break;if(a=b.shift())this.ya=a;if(a=b.shift())this.Ba=a;if(a=b.shift())this.Fa=a;if(a=b.shift())this.wa=a;if(a=b.shift())this.Aa=a;if(a=b.shift())this.T=a;if(a=b.shift())this.Ca=a;b.shift();if(a=b.shift())this.Da=a;if(a=b.shift())this.za=RegExp(a);break;case 3:if(a=b.shift())this.Ha=RegExp(a);break;case 5:this.B=!0;if(a=b.shift())this.f=a;if(a=b.shift())this.G=a;if(a=b.shift())this.lb=a;break;default:this.B=!0;if(a=b.shift())this.f=
a;if(a=b.shift())this.na=a}this.f.includes("^/")&&((b=this.Ga)?b="https?://"+b.slice(+b.startsWith("^"),-b.endsWith("$")||void 0):b=U.replaceAll(".","\\."),this.f=this.f.replaceAll("^/","^(?:"+b+")?/"))};e.aa=function(a){if(this.o&&this.R(arguments))switch(this.o){case 1:this.Kb(a);break;case 2:this.Gb(a);break;case 4:this.Hb(a);break;case 3:this.Jb(a);break;case 5:this.Ib(a)}};e.X=function(a){var b=this.a,c;for(c of document.getElementsByTagName("script"))!c.src&&a.test(c.innerText)&&b.postMessage([34,
null,-1,c.outerHTML]);b.postMessage([34,this.C()])};e.ab=function(a,b,c){if(this.hb&&b){var d=this.M(a);if(d){this.N.set(a,c);window.postMessage([1229212980,d,b],"/");return}}c(a)};e.Ub=function(a,b){if(a=this.m[a]){var c=this.N.get(a);c&&(this.N.delete(a),c(a,b))}};e.Xb=function(a){var b=a.data;if(Array.isArray(b)&&a.origin==U)switch(b[0]){case 1229212977:window.postMessage([1229212978,this.ea,this.B,this.nb,this.f,this.G],"/");this.hb=!0;break;case 1229212979:this.a.postMessage([36,b[1],b[2]]);
break;case 1229212981:this.Ub(b[1],b[2])}};e.Y=function(){var a=window.devicePixelRatio,b=document.width,c=document.body.scrollWidth;b&&c&&(a=b==c?0:b/c);return a};e.M=function(a){var b=a.h;b||(b=a.h=this.ea<<13|this.gb++,a.setAttribute("__idm_id__",b),this.m[b]=a);return b};e.J=function(a){a.s&&(window.clearTimeout(a.s),a.s=null);a.P&&(a.P.disconnect(),a.P=null);this.O&&this.O.unobserve(a);this.K&&this.K.unobserve(a);delete this.m[a.h];a.h=a.D=a.c=null};e.Pa=function(a,b,c){var d=this.M(a);if(b||
c){if(b?b==a.D:c==a.c)return;a.c=c||W+a.localName+"/"+b;a.D=b}a.P||(b=a.P=new MutationObserver(this.fa.bind(this)),b.observe(a,{attributes:!0,attributeFilter:["style"]}),b.observe(a.parentElement,{childList:!0}),this.O&&this.O.observe(a));1==this.o&&t(a,this.V)&&(a.Wa=!0,a.Cb=10);return d};e.F=function(a,b,c,d){if(b=this.Pa(a,b,c))d&&this.K&&this.K.observe(a),d=this.L(a),this.a.postMessage([41,b,a.localName,a.src||a.data,a.c,a.D,d])};e.tb=function(a,b,c,d,f,h){var l,m,p,k=window.getComputedStyle.bind(window);
try{var g=0;var q=document.activeElement;q&&L(q.localName)||(q=document.elementFromPoint(this.ka,this.la))&&!L(q.localName)&&(q=null);for(var n of document.querySelectorAll("video,audio,object,embed")){var r=n.localName,u,v="object"==r||"embed"==r;if(v){var A=n.type.toLowerCase();if(A.startsWith("text/")||A.startsWith("image/"))continue;if("embed"==r&&"application/x-shockwave-flash"!=A)continue}if(n.c&&!n.Wa&&(f||h))if(f?f==n.D:h==n.c)var x=n;else continue;else if(u=n.src||n.data)u!=a&&u!=b||(x=n);
else if(!v)for(var G of n.getElementsByTagName("source"))if((u=G.src)&&(u==a||u==b)&&(x=n))break;if(x)if("cover"==k(n).objectFit){var y=n;x=null}else break;if(!(y||q||l)){if(u){if((u==c||u==d)&&(l=n))continue;if("video"==r&&u.startsWith("data:audio/"))continue}var z=n.clientWidth,B=n.clientHeight;if(z&&B){var O=n.getBoundingClientRect();if(!(0>=O.right+window.scrollX||0>=O.bottom+window.scrollY))if("hidden"==k(n).visibility||n.Z)"video"==r&&(p||(p=n));else{v=z*B;if(g<v&&1.35*z>B&&z<3*B){g=v;var aa=
n}m||(m=n)}}}}}catch(ba){}(n=x||y||q||l)?"video"!=n.localName&&"hidden"==k(n).visibility&&(n=null):n=aa||m||p;n&&("embed"!=n.localName||n.clientWidth||n.clientHeight||(a=n.parentElement,"object"==a.localName&&(n=a)),this.Pa(n,f,h));return n};e.sb=function(a,b,c){var d=null,f,h=browser.runtime.Ta,l;for(l of document.getElementsByTagName("iframe")){var m=l.Va;null==m&&h&&(m=l.Va=h(l));if(m==a){d=l;break}else d||!(f=l.src)||f!=b&&f!=c||(d=l)}return d&&this.M(d)};e.L=function(a){var b=null;try{var c=
window.getComputedStyle(a),d=a.getBoundingClientRect(),f=this.S,h=Math.round(d.width),l=Math.round(d.height);if("hidden"==c.visibility)return h>5*l?null:!1;if(0==c.opacity||a.Z)return!1;if(1==this.o&&0==a.offsetTop+a.offsetHeight){for(var m=a;m=m.parentElement;){var p=window.getComputedStyle(m);if("block"!=p.display)break;if(0==p.opacity)return!1}d=a.parentElement.parentElement.getBoundingClientRect();f=0}var k=Math.round(d.left)+a.clientLeft,g=Math.round(d.top)+a.clientTop,q=d=0;m=a;p=c;for(var n,
r;f--&&"block"==p.display&&(n=m.parentElement)&&"div"==n.localName;m=n,p=r){r=window.getComputedStyle(n);d-=m.offsetLeft;q-=m.offsetTop;if("hidden"==r.overflowX){var u=h-n.offsetWidth-d;0<d&&(h-=d,k+=d);0<u&&(h-=u);f=0}if("hidden"==r.overflowY){var v=l-n.offsetHeight-q;0<q&&(l-=q,g+=q);0<v&&(l-=v);f=0}}switch(a.localName){case "video":document.contains(a)&&(a.videoWidth||a.c||1>a.readyState&&2==a.networkState)&&(b=!1);if(15>h||10>l)return b;break;case "audio":if(1>h&&1>l)return b;var A=!0}var x=document.documentElement,
G=x.scrollWidth||x.clientWidth,y=x.scrollHeight||x.clientHeight;if(k>=G||g>=y||A&&!k&&!g)return b;0==k&&g==-y&&h==G&&l==y&&(g=0);var z=this.Y();q=a.Cb||0;b=[k,g+q,k+h,g+l-q,z]}catch(B){}return b};e.ob=function(a){var b=a.Db;if(b){b=document.elementsFromPoint((b.left+b.right)/2,(b.top+b.bottom)/2);for(var c,d;(c=b.shift())&&!c.isSameNode(a);){var f=window.getComputedStyle(c);if("visible"==f.visibility&&"0"!=f.opacity&&!S(f.backgroundColor)){d=!0;break}}a.Z=d}};e.C=function(){var a=T?80:90;try{var b=
window.top.document.title}catch(c){}b||(b=(b=document.head.querySelector('meta[property="og:title"]'))&&b.getAttribute("content"),a=70);b&&(b=b.replace(/^\(\d+\)/,"").replace(/[ \t\r\n\u25B6]+/g," "),b=new String(b.trim()),b.src=a);return b};e.xb=function(){if(!document.elementsFromPoint)return 0;var a=document.documentElement,b=a.clientWidth||a.offsetWidth;a=(a.clientHeight||window.innerHeight)/4;var c=document.elementsFromPoint(0,0),d=0,f=0,h=0,l;for(l of c)if(l.offsetWidth>=b){var m=window.getComputedStyle(l);
.95<=m.opacity&&(c=m.zIndex,"fixed"==m.position?(m=l.offsetHeight+l.offsetTop,d<m&&m<a&&(d=m,f=c)):h<c&&(h=c))}f<h&&(d=0);return d};e.ub=function(a,b,c,d,f,h,l,m,p){m&&P("text/javascript",m);this.kb=a;this.ea=b;if(d){this.ca=d;try{window.frameElement&&(window.frameElement.Va=d)}catch(k){}}this.Ua(h);f&&this.Yb(f,H(arguments,9));p&&(this.b(2,window,"message",this.Xb),P("text/javascript",p));"loading"==document.readyState?this.ia=!0:this.aa()};e.vb=function(a){this.ja&&this.g&&(this.g=0,this.ma=window.setTimeout(this.ga.bind(this,
!1),3E3));this.aa(!0);a&&this.Ua();for(var b of w(this.m))this.ob(b)};e.Ua=function(a){if(this.R(arguments)){var b=[21,this.$b||location.href,document.referrer];a&&b.push(document.getElementsByTagName("video").length,document.getElementsByTagName("audio").length);this.a.postMessage(b)}};e.zb=function(a){var b=a?this.R(arguments):1;if(0<b||0>b&&1!=this.o){b=this.C();var c=this.Y(),d=this.xb();this.a.postMessage([24,b,b&&b.src,c,d])}};e.Bb=function(a,b,c,d,f){c||(c=this.sb(b,d,f));d=(d=c&&this.m[c])&&
this.L(d);this.a.postMessage([22,a,b,c,d])};e.yb=function(a,b){var c=document.getElementsByTagName("a"),d;for(d of c)try{if(d.href==b){var f=d.download||null;var h=d.innerText.trim()||d.title||null;break}}catch(l){}this.a.postMessage([35,a,f,h])};e.Ab=function(a,b,c,d,f,h,l,m){if(this.R(arguments)){var p=[23,a,b,!1],k,g,q;if(b)b&&((k=this.m[b])||(p[3]=!0));else{if(k=this.tb(c,d,f,h,m,l)){if(this.na&&(g=t(k,this.na)))var n=200;else if(g=k.getAttribute("operadetachedviewtitle"))n=130;p[2]=b=k.h;p[5]=
k.localName;p[6]=k.src||k.data}else if(m||l)p[3]=!0;!g&&(g=this.C())&&(n=g.src,(q=X.exec(g))&&(g=q[1]));p[7]=g;p[8]=n}k&&(g=this.L(k),null!=g||document.contains(k)?p[4]=g:(this.J(k),p[3]=!0));this.a.postMessage(p)}};e.wb=function(a,b,c,d){var f=d?RegExp(d,"i"):null;d=this.Sa(document,f,b);var h=document.getElementsByTagName("iframe"),l;for(l of h)try{var m=l.contentDocument;m&&!l.src&&I(d,this.Sa(m,f,b))}catch(p){}a=[27,a,this.ca,d.length];c||(a[4]=d,a[5]=location.href,T&&(a[6]=location.href,a[7]=
document.title));this.a.postMessage(a)};e.Sa=function(a,b,c){var d=[],f={},h="",l="",m=!c;if(c){var p=a.getSelection();if(!p||p.isCollapsed&&!p.toString().trim())return d}for(var k of a.getElementsByTagName("a"))if(m||p.containsNode(k,!0))try{var g=k.href;g&&!f[g]&&b.test(g)&&(f[g]=d.push([g,2,k.download||null,k.innerText.trim()||k.title]));c&&f[g]&&(l+=k.innerText,l+="\n")}catch(n){}for(k of a.getElementsByTagName("area"))if(m||p.containsNode(k,!0))try{(g=k.href)&&!f[g]&&b.test(g)&&(f[g]=d.push([g,
2,null,k.alt]))}catch(n){}for(k of a.getElementsByTagName("img"))if(m||p.containsNode(k,!0))try{(g=k.src)&&!f[g]&&b.test(g)&&(f[g]=d.push([g,3,null,"<<<=IDMTRANSMITIMGPREFIX=>>>"+k.alt])),m&&k.onclick&&(h+=k.onclick,h+="\n")}catch(n){}if(c){if(h=p.toString()){c=this.I(l);for(g of this.I(h))g&&!f[g]&&b.test(g)&&!c.includes(g)&&(f[g]=d.push([g,1]))}for(k of a.getElementsByTagName("textarea"))if(a=k.selectionStart,h=k.selectionEnd,(c=p.isCollapsed&&a<h)||p.containsNode(k,!0))try{var q=c?k.value.substring(a,
h):k.value;for(g of this.I(q))g&&!f[g]&&b.test(g)&&(f[g]=d.push([g,1]))}catch(n){}}else{for(k of a.getElementsByTagName("iframe"))try{(g=k.src)&&!f[g]&&b.test(g)&&(f[g]=d.push([g,4]))}catch(n){}for(k of a.getElementsByTagName("script"))h+=k.innerText,h+="\n";if(h)for(g of this.I(h))g&&!f[g]&&b.test(g)&&(f[g]=d.push([g,5]))}return d};e.I=function(a){if(!this.fb){var b="\\b\\w+://(?:[%T]*(?::[%T]*)?@)?[%H.]+\\.[%H]+(?::\\d+)?(?:/(?:(?: +(?!\\w+:))?[%T/~;])*)?(?:\\?[%Q]*)?(?:#[%T]*)?".replace(/%\w/g,
function(d){return this[d]}.bind({"%H":"\\w\\-\u00a0-\ufeff","%T":"\\w\\-.+*()$!,%\u00a0-\ufeff","%Q":"^\\s\\[\\]{}()"}));this.fb=RegExp(b,"gi")}for(var c=[];b=this.fb.exec(a);)c.push(b.shift());return c};e.R=function(a){var b=this.g;b||(a=E(a&&a.callee?a:arguments),a.unshift(arguments.callee.caller),this.da.push(a));return b};e.Za=function(a){try{var b=window.top.document.getElementsByTagName("title")[0]}catch(c){}this.g=a&&b?-1:1;b&&(a=this.ja,a||(this.ja=a=new MutationObserver(this.ga.bind(this))),
a.observe(b,{childList:!0}));try{this.O=new ResizeObserver(this.fa.bind(this))}catch(c){}try{this.K=new IntersectionObserver(this.fa.bind(this),{threshold:.2})}catch(c){}this.ia&&(this.ia=!1,this.aa());for(a=this.da;b=a.shift();)b.shift().apply(this,b)};e.fa=function(a){if(this.a)for(var b of a)if(a=b.target,a.h)if(document.contains(a)){var c=b.isIntersecting;null!=c&&(a.Z=!c,a.Db=c?b.intersectionRect:null);a.s&&window.clearTimeout(a.s);a.s=window.setTimeout(this.Mb.bind(this,a),200)}else this.a.postMessage([23,
null,a.h,!0]),this.J(a)};e.Mb=function(a){if(!this.a)return this.J(a);a.s=null;var b=document.contains(a);if(b){var c=this.L(a);if(1==this.o&&a.Wa)if(c){var d=t(a,this.V);d&&d.href&&d.href!=a.c&&this.F(a,null,d.href)}else a.c=a.D=null,b=!1}else this.J(a);this.a.postMessage([23,null,a.h,!b,c])};e.ga=function(a){if(a)window.clearTimeout(this.ma),this.ma=window.setTimeout(this.ga.bind(this,!1),1E3);else{0>this.g?this.g=1:++this.g;for(var b=this.da;a=b.shift();)a.shift().apply(this,a)}};e.Lb=function(a){var b=
a.target,c=b.localName;L(c)&&a.url&&(b=this.M(b),this.a.postMessage([25,b,c,a.url]))};e.$a=function(a){!a.repeat&&K[a.keyCode]&&this.a.postMessage([31,a.keyCode,"keydown"==a.type])};e.Pb=function(a){this.mb&&this.a.postMessage([28]);if(0==a.button){var b=a.view.getSelection();b&&b.isCollapsed&&!b.toString().trim()&&(this.l=1);this.a.postMessage([32,a.button,!0])}};e.Rb=function(a){if(0==a.button){this.ka=a.clientX;this.la=a.clientY;this.a.postMessage([32,a.button,!1]);var b=a.view.getSelection();
b&&this.l&&(this.l=b.isCollapsed&&!b.toString().trim()?0:2)&&this.a.postMessage([26,a.clientX,a.clientY,this.Y()])}};e.Qb=function(){2==this.l&&(this.l=0)};e.Ob=function(a){a=a.target;"a"==a.localName&&this.a.postMessage([39,a.hasAttribute("download"),a.href,a.download])};e.Wb=function(){this.a.postMessage([29])};e.Vb=function(a){a=a.target;this.a.postMessage([30,a.innerWidth,a.innerHeight])};e.Nb=function(){this.l=0;this.a.postMessage([33])};e.b=function(a,b,c,d,f){var h=E(arguments);h[3]=d.bind(this);
this.ha.push(h);0>a?(b=b[c],b.addListener.apply(b,h.slice(3))):b.addEventListener.apply(b,h.slice(2))};e.bb=function(a){for(var b=this.ha,c=0;c<b.length;c++){var d=b[c][0];if(!a||a==d){var f=b.splice(c--,1).pop(),h=f.splice(0,2).pop();0>d?(h=h[f.shift()],h.removeListener.apply(h,f)):h.removeEventListener.apply(h,f)}}};e.Kb=function(a){V="youtube";W="idmrs://youtube/";var b=this.Oa.exec(location.pathname+location.search);if(b){var c=t(document.body,this.Na);c&&this.F(c,b[1])}if(!a){a=this.a;var d,
f,h=0,l;for(l of document.getElementsByTagName("script")){if(l.src){if(b=this.U.exec(l.src))h|=1,this.A[b[1]]?d=b[1]:c=l.src}else if(b=this.Ma.exec(l.innerText))h|=2,this.A[b[1]]&&(f=parseInt(b[1],10));else if(this.Ia.test(l.innerText)){h|=4;var m=l.outerHTML}if(7==h)break}if(f||d)b={},b[118]=f,b[124]=d,a.postMessage([37,1,2,b]);a.postMessage([34,this.C(),null,m]);c&&(m=new XMLHttpRequest,m.responseType="text",m.timeout=1E4,m.onreadystatechange=this.Zb.bind(this,c,m),m.open("GET",c,!0),m.send());
this.S=2}};e.Zb=function(a,b){if(4==b.readyState){var c=this.U.exec(a);if((a=(a=this.Ja.exec(b.response))&&parseInt(a[1]||a[2],10))&&(!this.A[a]||!this.A[c[1]])){var d=this.Ka.exec(b.response);b=this.La.exec(b.response);if(d&&b&&d[2]==b[1]){c=c&&c[1];var f={};f[118]=a;f[119]=d[0];f[120]=b[0];f[124]=c;this.a.postMessage([37,1,1,f])}}}};e.Gb=function d(b,c){b?(c&&b.shift().disconnect(),this.ba.disconnect(),this.eb.disconnect(),this.cb.clear()):(this.X(this.ua),this.ba=new MutationObserver(this.qb.bind(this)),
this.eb=new MutationObserver(this.pb.bind(this)),this.cb=new Set,this.S=3,this.i.startsWith("$")||(this.i="$<"+this.i.slice(1)+"<"),this.j.startsWith("$")||(this.j="$<"+this.j.slice(1)+"<"),this.u.startsWith("$")||(this.u="$*"+this.u),this.v.startsWith("$")||(this.v="$*"+this.v));if(c=this.jb=t(document.body,this.sa)){if(b=this.ba,b.observe(c,{childList:!0}),!this.Ra(c,!0)&&(c=t(c,this.ta))){var f=t(c,this.i);f&&b.observe(c,{childList:!0});b.observe(f||c.parentNode,{childList:!0})}}else!b&&(c=t(document.body,
this.pa))&&(f=new MutationObserver(d.bind(this,b=[])),b.push(f),f.observe(c,{childList:!0}))};e.Ra=function(b,c){var d=this.ba,f=this.i,h=this.u,l=this.eb,m=this.cb,p=0,k;for(k of t(b,h,[]))m.has(k)||t(k,h)||(m.add(k),l.observe(k,{childList:!0,subtree:!0}),c&&(b=t(k,f))&&(d.observe(b,{childList:!0}),p++),J(k.getElementsByTagName("video"),this.W.bind(this)));return p};e.qb=function(b){var c=this.jb,d;for(d of b){b=d.target.isSameNode(c);for(var f of d.addedNodes)1==f.nodeType&&this.Ra(f,b)}};e.pb=
function(b){var c=this.N,d=this.j,f;for(f of b)for(var h of f.addedNodes)if(1==h.nodeType)if(b=h.getElementsByTagName("video"),b.length)J(b,this.W.bind(this));else for(var l of c){b=l.shift();var m=t(b,d);m&&m.contains(h)&&this.W(b)}};e.W=function(b){if(!b.c){var c=t(b,this.j),d,f=c&&t(c,this.va);if(!f){for(var h=this.oa,l=this.ra,m=F.bind(["div","span","a"]),p,k,g,q,n,r=c;r&&l--&&m(r.localName);r=r.parentNode){var u=k=r,v=h+":scope:first-child:only-of-type";for(d=0;"<"==v[d];d++);d&&(v=v.slice(d));
for(u=u.closest(v);u&&d--;u=u.parentElement);if(d=u)break;if((g=r.previousSibling)&&"div"==g.localName){p||(p=r.querySelector('div[role="slider"]'));1==(n=r.querySelectorAll(h)).length?d=n[0]:(q=r.nextSibling)&&1==(n=q.querySelectorAll("ul:scope "+h)).length?d=n[0]:p&&1<(n=g.querySelectorAll(h)).length&&(d=n[n.length-1]);break}}!d&&k&&1==(n=t(k,this.v,[])).length&&(d=n[0]);!d&&c&&(d=c.querySelector(":scope >"+h));d&&(d=d.href);!d&&1==document.getElementsByTagName("video").length&&(f=this.qa.exec(location.href))&&
(f=f[1])}f||d?this.F(b,f,d):this.ab(b,this.ib,this.rb.bind(this))}};e.rb=function(b,c){c&&this.F(b,c)};e.Hb=function(b){!b&&(this.X(this.xa),b=t(document,this.Ea))&&(C(b,this.ya,this.Eb.bind(this)),C(b,this.Ba,this.$.bind(this)),C(b,this.Fa,this.$.bind(this)),C(document.body,this.Aa,this.$.bind(this)))};e.Xa=function(b,c,d){!c&&1==document.getElementsByTagName("video").length&&(c=this.za.exec(location.href))&&(c=c[1]);this.F(b,c,d,!0)};e.Eb=function(b){for(var c of t(b,this.wa,[]))J(t(c,this.T,[]),
this.Ya.bind(this))};e.$=function(b){J(t(b,this.T,[]),this.Ya.bind(this))};e.Ya=function(b){if(!b.c){var c=t(b,this.Ca);c?this.Xa(b,null,c):this.ab(b,this.Da,this.Fb.bind(this))}};e.Fb=function(b,c){c&&this.Xa(b,c)};e.Jb=function(b){b||this.X(this.Ha)};e.Ib=function(b){if(!b){var c=t(document.body,this.lb);c&&(b=this.C(),c=c.outerHTML,this.a.postMessage([34,b,null,c.slice(0,c.indexOf(">")+1)]))}};function P(b,c){var d=b.startsWith("image/")?"img":"script";d=document.createElement(d);d.src="data:"+
b+";base64,"+c;d.onload=d.remove.bind(d);document.documentElement.appendChild(d)}function t(b,c,d){function f(q,n,r){for(;r&&n--;)r=r.parentElement;r&&(isNaN(q)||this.push(q),this.push(r));return r}if(!c)return d;var h,l,m=!0,p=d||[],k=c.split(R);1==k.length?(k[0].startsWith("<")&&k.unshift(k.shift().slice(1)+"<"),k.unshift(">",NaN)):k.shift();for(;b&&(h=k.shift());){c=parseInt(k.shift(),10);var g=k.shift().trim();for(l=1;"<"==g[g.length-l];l++);--l&&(g=g.slice(0,-l).trim());switch(h){case "<":b=
Q(g?b.closest(g):b,l);break;case ">":b=Q(b.querySelector(g),l);break;case "{":b.closest(g)&&(b=null);break;case "}":b.querySelector(g)&&(b=null);break;case "&":b=f.call(p,c,l,b.querySelector(g));m=!1;break;case "*":b.querySelectorAll(g).forEach(f.bind(p,c,l));m=!1;break;case "+":g=g?g.endsWith(":scope")?b.closest(g):b.querySelector(g):b;f.call(p,c,l,g);m=!1;break;case "=":if(g=b.getAttribute(g))return g;m=!1;break;case "@":if(g=b.textContent.trim())return g;m=!1}}return p.length?p:m&&b||d}function C(b,
c,d,f,h,l){if(null==f){f=t(b,c,[]);l=new MutationObserver(C.bind(null,b,c,d,f));l.observe(b,{childList:!0});for(var m of f)l.observe(m,{childList:!0});f.length&&d(f.H(-1))}else for(var p of h){for(var k of p.addedNodes)if(1==k.nodeType)if(h=t(b,c,[]).slice(f.length),h.length){I(f,h);for(m of h)l.observe(m,{childList:!0});for(var g of h.pop().children)d(g)}else p.target.isSameNode(f.H(-1))&&d(k);for(k of p.removedNodes)if(1==k.nodeType)for(h=0;h<f.length;h++)if(k.contains(f[h])){f.splice(h);break}}}
function Q(b,c){for(;b&&c--;b=b.parentElement);return b}function Z(b,c){c&&(b[c]=!0);return b}var Y=Object.isExtensible;try{Y(null)}catch(b){Y=function(c){return c instanceof Object}}String.prototype.replaceAll||(String.prototype.replaceAll=function(b,c){return this.split(b).join(c)});new N}!0;
