name: Windows with Python and Chrome

on:
  schedule:
    - cron: '5 21 * * *' # 每天凌晨0点执行
  push:
    branches:
      - main # 或者你想要监听的分支名
  workflow_dispatch: # 允许手动触发

jobs:
  run-browser-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 # 根据你的需求选择Python版本

    - name: Install Google Chrome
      shell: powershell
      run: |
        $chromeInstallerPath = 'https://dl.google.com/tag/s/installdataindex/update2/installers/ChromeStandaloneSetup64.exe' # 替换为你的实际路径
        Start-Process msiexec.exe -Wait -ArgumentList '/I', $chromeInstallerPath, '/quiet'

    - name: Download and install ChromeDriver
      shell: bash
      run: |
        CHROME_DRIVER_VERSION=$(curl --silent "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
        curl -Lo chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_win32.zip
        7z x chromedriver.zip -o./
        mv ./chromedriver.exe $GITHUB_WORKSPACE
        echo "##[add-path]$GITHUB_WORKSPACE"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run browser automation script
    #   run: python your_automation_script.py

    - name: Clean up (Optional)
      if: always()
      run: |
        Remove-Item -Force "./chromedriver.exe"

# 示例requirements.txt文件内容：
# requests==2.25.1
# selenium==3.141.0
# webdriver-manager==3.5.2
