name: Windows with Python and Chrome

on:
  schedule:
    - cron: '5 21 * * *' # 每天凌晨0点执行
  workflow_dispatch: # 允许手动触发

jobs:
  run-browser-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 # 根据你的需求选择Python版本

    - name: Install Google Chrome
      shell: powershell
      run: |
        $chromeInstallerPath = 'https://dl.google.com/tag/s/installdataindex/update2/installers/ChromeStandaloneSetup64.exe' # 替换为你的实际路径
        Start-Process msiexec.exe -Wait -ArgumentList '/I', $chromeInstallerPath, '/quiet'

    - name: Add ChromeDriver to PATH
      shell: powershell
      run: |
        echo "$($env:GITHUB_WORKSPACE)\chromedriver.exe" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
   
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    - name: Run browser automation script
      run: python test.py
      # 如果需要查看详细的实时输出，可以加上以下内容：
      # 注意：verbose不是必需的，但有助于在日志中看到更多详细信息
      env:
        VERBOSE: true
      shell: bash
      # 输出会被自动记录，无需额外设置

