name: Windows Python Build and Run

on:
  schedule:
    - cron: '0 */3 * * *'  # 每三天执行一次，精确到小时（每3天的每个小时的第0分钟执行）
  workflow_dispatch:  # 仍然保留手动触发

env:
  PYTHON_VERSION: 3.9
  CACHE_KEY: windows-pip-${{ github.sha }}

jobs:
  build-and-run:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Cache pip dependencies
      id: cache-pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ env.CACHE_KEY }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Save Cache after installing dependencies
      if: steps.cache-pip.outputs.cache-hit != 'true'
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ env.CACHE_KEY }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Run Python Program
      run: python ./test.py
      env:
        # 如果你的脚本需要环境变量，这里可以添加
        VAR_NAME: value
      shell: bash

# 注意替换 `your_script.py` 为您的实际Python脚本名称
